[package]
name = "metabase-utils"
version = "0.0.1"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2018"

[dependencies]
csv = "1.4"
reqwest = { version = "0.12", features = ["blocking"] }
serde_json = "1.0.145"
